import { icons } from "../constants/icons"

const weatherIconsDay = {
    0: {label: "Clear Sky", icon: "clearDay"},
    1: {label: "Mainly Clear", icon: "cloudy1day"},
    2: {label: "Partly Cloudy", icon: "cloudy2day"},
    3: {label: "Overcast", icon: "cloudy"},
    45: {label: "Fog", icon: "fogDay"},
    48: {label: "Icy Fog", icon: "fog"},
    51: {label: "Light Drizzle", icon: "rainy1day"},
    53: {label: "Drizzle", icon: "rainy2day"},
    55: {label: "Heavy Drizzle", icon: "rainy3day"},
    61: {label: "Light Rain", icon: "rainy1"},
    63: {label: "Rain", icon: "rainy2"},
    65: {label: "Heavy Rain", icon: "rainy3"},
    71: {label: "Light Snow", icon: "snowy1"},
    73: {label: "Snow", icon: "snowy2"},
    75: {label: "Heavy Snow", icon: "snowy3"},
    80: {label: "Light Showers", icon: "rainy1day"},
    81: {label: "Showers", icon: "rainy2day"},
    82: {label: "Heavy Showers", icon: "rainy3day"},
    95: {label: "Thunderstorm", icon: "scatteredThunderstorms"},
    96: {label: "Thunderstorm + Hail", icon: "thunderstorms"},
    99: {label: "Heavy Thunderstorm + Hail", icon: "severThunderstorms"},
}

const weatherIconsNight = {
    0: {label: "Clear Sky", icon: "clearNight"},
    1: {label: "Mainly Clear", icon: "cloudy1night"},
    2: {label: "Partly Cloudy", icon: "cloudy2night"},
    3: {label: "Overcast", icon: "cloudy"},
    45: {label: "Fog", icon: "fogNight"},
    48: {label: "Icy Fog", icon: "fog"},
    51: {label: "Light Drizzle", icon: "rainy1night"},
    53: {label: "Drizzle", icon: "rainy2night"},
    55: {label: "Heavy Drizzle", icon: "rainy3night"},
    61: {label: "Light Rain", icon: "rainy1"},
    63: {label: "Rain", icon: "rainy2"},
    65: {label: "Heavy Rain", icon: "rainy3"},
    71: {label: "Light Snow", icon: "snowy1"},
    73: {label: "Snow", icon: "snowy2"},
    75: {label: "Heavy Snow", icon: "snowy3"},
    80: {label: "Light Showers", icon: "rainy1night"},
    81: {label: "Showers", icon: "rainy2night"},
    82: {label: "Heavy Showers", icon: "rainy3night"},
    95: {label: "Thunderstorm", icon: "scatteredThunderstorms"},
    96: {label: "Thunderstorm + Hail", icon: "thunderstorms"},
    99: {label: "Heavy Thunderstorm + Hail", icon: "severThunderstorms"},
}

// const weatherIconsNight = {
//     0: {label: "Clear Sky", icon: icons.clearNight},
//     1: {label: "Mainly Clear", icon: icons.cloudy1night},
//     2: {label: "Partly Cloudy", icon: icons.cloudy2night},
//     3: {label: "Overcast", icon: icons.cloudy},
//     45: {label: "Fog", icon: icons.fogNight},
//     48: {label: "Icy Fog", icon: icons.fog},
//     51: {label: "Light Drizzle", icon: icons.rainy1night},
//     53: {label: "Drizzle", icon: icons.rainy2night},
//     55: {label: "Heavy Drizzle", icon: icons.rainy3night},
//     61: {label: "Light Rain", icon: icons.rainy1},
//     63: {label: "Rain", icon: icons.rainy2},
//     65: {label: "Heavy Rain", icon: icons.rainy3},
//     71: {label: "Light Snow", icon: icons.snowy1},
//     73: {label: "Snow", icon: icons.snowy2},
//     75: {label: "Heavy Snow", icon: icons.snowy3},
//     80: {label: "Light Showers", icon: icons.rainy1night},
//     81: {label: "Showers", icon: icons.rainy2night},
//     82: {label: "Heavy Showers", icon: icons.rainy3night},
//     95: {label: "Thunderstorm", icon: icons.scatteredThunderstorms},
//     96: {label: "Thunderstorm + Hail", icon: icons.thunderstorms},
//     99: {label: "Heavy Thunderstorm + Hail", icon: icons.severThunderstorms},
// }

export {weatherIconsDay, weatherIconsNight};